### ISSUE TITLE
Whitesource in CI

### ISSUE THREAD

**Issue by kollstrom** [birch-wood/tanK#14]
See https://github.com/marketplace/whitesource-bolt

**Comment by kollstrom** [comment]
Should we just use Whitesource like this?
https://github.com/apps/whitesource-for-github-com

**Comment by kollstrom** [comment]
More detailed HOW-TO: https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com

**Comment by martinemdal** [comment]
I think so, looks like the best way to integrate whitesource on github

**Comment by kollstrom** [comment]
Alright, will do it that way then.
